name: manual ci 

on:
  workflow_dispatch:

jobs:
   job1:
      runs-on: ubuntu-latest

      steps:
        - name: just run
          env:
            welcome: "vishwa"
          run: | 
            echo "mass prince"
            echo " ${{ vars.MASS_USER }} "
            echo " $welcome"
